{
 "title": "${{values.name}} - Dashboard",
 "tags": [ "${{values.cluster}}" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   { "name": "alert_groups_total", "label": "alert_groups_total", "query": { "query": "metrics(alert_groups_total)" } },
   {
    "name": "alert_groups_response_time_seconds_count",
    "label": "alert_groups_response_time_seconds_count",
    "query": {
     "query": "metrics(alert_groups_response_time_seconds_count)"
    }
   },
   {
    "name": "alert_groups_response_time_seconds_sum",
    "label": "alert_groups_response_time_seconds_sum",
    "query": {
     "query": "metrics(alert_groups_response_time_seconds_sum)"
    }
   },
   {
    "name": "alert_groups_response_time_seconds_bucket",
    "label": "alert_groups_response_time_seconds_bucket",
    "query": {
     "query": "metrics(alert_groups_response_time_seconds_bucket)"
    }
   },
   {
    "name": "user_was_notified_of_alert_groups_total",
    "label": "user_was_notified_of_alert_groups_total",
    "query": {
     "query": "metrics(user_was_notified_of_alert_groups_total)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(${alert_groups_total},slug)"
    }
   },
   {
    "name": "team",
    "label": "Team",
    "query": {
     "query": "label_values(${alert_groups_total}{slug=~\"$instance\"},team)"
    }
   },
   {
    "name": "integration",
    "label": "Integration",
    "query": {
     "query": "label_values(${alert_groups_total}{team=~\"$team\",slug=~\"$instance\"},integration)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 0, "y": 0 },
   "options": {
    "content": "<div>\n  <img src=\"/public/plugins/grafana-oncall-app/assets/img/logo.svg\">\n</div>"
   }
  },
  { "type": "text", "gridPos": { "h": 2, "w": 23, "x": 1, "y": 0 }, "options": { "content": "# Grafana OnCall Insights" } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 2 },
   "options": {
    "content": "📣 This is a read-only dashboard. To make a copy, click \"Settings\" and \"Save as\".\n\n📝 If you see *\"No data\"* errors, check the right datasource is selected\nand that you have already used and setup the [OnCall](/a/grafana-oncall-app/alert-groups) plugin.\nYou can also try [re-importing the dashboard](/plugins/grafana-oncall-app?page=dashboards)\nto confirm you have the latest updates. If you just copied the dashboard,\nyou may need to reload it."
   }
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Total alert groups",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(sum(avg without(pod, instance) ($alert_groups_total{slug=~\"$instance\", team=~\"$team\", integration=~\"$integration\"}))[1d:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total alert groups by state",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 5, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (state) (avg without(pod, instance) ($alert_groups_total{slug=~\"$instance\", team=~\"$team\", integration=~\"$integration\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New alert groups for selected period",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(max_over_time(sum(avg without(pod, instance) ($alert_groups_total{slug=~\"$instance\", team=~\"$team\", integration=~\"$integration\"}))[1d:])[$__range:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mean time to respond (MTTR)",
   "type": "stat",
   "description": "Mean time between the start and first action of all alert groups for the last 7 days",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time((sum($alert_groups_response_time_seconds_sum{slug=~\"$instance\", team=~\"$team\", integration=~\"$integration\"}) / sum($alert_groups_response_time_seconds_count{slug=~\"$instance\", team=~\"$team\", integration=~\"$integration\"}))[$__range:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MTTR changed for period",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "avg(sum($alert_groups_response_time_seconds_sum{slug=~\"$instance\", team=~\"$team\", integration=~\"$integration\"}) / sum($alert_groups_response_time_seconds_count{slug=~\"$instance\", team=~\"$team\", integration=~\"$integration\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New alert groups during time period",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "increase(max_over_time(sum by (integration) (avg without(pod, instance) ($alert_groups_total{slug=~\"$instance\", team=~\"$team\", integration=~\"$integration\"}))[30m:])[1h:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MTTR changed for period",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(sum($alert_groups_response_time_seconds_sum{slug=~\"$instance\", team=~\"$team\", integration=~\"$integration\"}) / sum($alert_groups_response_time_seconds_count{slug=~\"$instance\", team=~\"$team\", integration=~\"$integration\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Integrations data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Alert groups by Integration",
   "type": "table",
   "gridPos": { "h": 23, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sort_desc(max_over_time(sum by(integration) (avg without(pod, instance)($alert_groups_total{slug=~\"$instance\", team=~\"$team\", integration=~\"$integration\"}))[1d:]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mean time to respond (MTTR) by Integration",
   "type": "table",
   "gridPos": { "h": 23, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sort_desc(avg_over_time((sum by (integration)($alert_groups_response_time_seconds_sum{slug=~\"$instance\", team=~\"$team\", integration=~\"$integration\"}) / sum by (integration)($alert_groups_response_time_seconds_count{slug=~\"$instance\", team=~\"$team\", integration=~\"$integration\"}))[$__range:]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Notified alert groups by Users (based on all Integrations)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 }
  },
  {
   "title": "New alert groups notifications during time period",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "increase(max_over_time(sum by (username) (avg without(pod, instance) ($user_was_notified_of_alert_groups_total{slug=~\"$instance\"}))[30m:])[1h:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New alert groups notifications in total",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "sort_desc(max_over_time(sum by(username) (avg without(pod, instance)($user_was_notified_of_alert_groups_total{slug=~\"$instance\"}))[1d:]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New alert groups notifications for period",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sort_desc(increase(max_over_time(sum by (username) (avg without(pod, instance) ($user_was_notified_of_alert_groups_total{slug=~\"$instance\"}))[1h:])[$__range:]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Teams data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Alert groups by Team",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 79 },
   "targets": [
    {
     "expr": "sort_desc(max_over_time(sum by(team) (avg without(pod, instance)($alert_groups_total{slug=~\"$instance\", team=~\"$team\", integration=~\"$integration\"}))[1d:]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mean time to respond by Team (MTTR)",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sort_desc(avg_over_time((sum by(team) ($alert_groups_response_time_seconds_sum{slug=~\"$instance\", team=~\"$team\", integration=~\"$integration\"}) / sum by(team)($alert_groups_response_time_seconds_count{slug=~\"$instance\", team=~\"$team\", integration=~\"$integration\"}))[$__range:]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}